services:
  database:
    image: mongo
    restart: always
    volumes:
      - law-fulldev-database:/data/db
  frontend:
    image: lawassist/frontend:dev-latest
    volumes:
      - .:/workspace:cached
      - frontend-dev-node-module:/workspace/FE/node_modules
    environment:
      - NEXT_PUBLIC_API_HOST=http://localhost:29003
      - NEXTAUTH_URL=http://localhost:29002/
    command: sleep infinity
    network_mode: service:backend
  backend:
    image: lawassist/backend:dev-latest
    volumes:
      - .:/workspace:cached
      - backend-dev-node-module:/workspace/BE/node_modules
    environment:
      - MONGODB_URI=mongodb://localhost:27017/law_linking
    command: sleep infinity
    network_mode: service:database
volumes:
  law-fulldev-database:
  frontend-dev-node-module:
  backend-dev-node-module:
