services:
  mongo:
    container_name: law-mongodb
    image: mongo
    restart: always
    ports:
      - 27018:27017
    networks:
      - law_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
      MONGO_INITDB_DATABASE: law_linking
    volumes:
      - law_mongodata:/data/db

  # mongo-express:
  #   container_name: law-mongo-express
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/law_linking
  #     ME_CONFIG_BASICAUTH: false
  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - law_network
    container_name: dacn242-frontend-app
    image: dacn242-frontend-app:0.0
    env_file:
      - ./FE/.env
  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - law_network
    container_name: dacn242-backend-app
    image: dacn242-backend-app:0.0
    env_file:
      - ./BE/.env
    volumes:
      - law_backend_server:/app/src
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096  # Increase the memory limit to 4GB
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          memory: 4g  # Limit the container to 4GB of memory
volumes:
  law_mongodata:
    driver: local
  law_backend_server:
    driver: local
networks:
  law_network:
    driver: bridge