version: "3.8"

services:
  backend:
    image: kanghcmut/lvtn-backend-app:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - "29001:29001"
    deploy:
      update_config:
        order: start-first
    pull_policy: always

  frontend:
    image: kanghcmut/lvtn-frontend-app:latest
    restart: always
    depends_on:
      - backend
    ports:
      - "29000:29000"
    env_file:
      - ./.env
    environment:
      - NEXTAUTH_URL:https://pl.thuanle.me 
      - NEXT_SERVER_API_HOST:https://api-pl.thuanle.me
      - NEXT_PUBLIC_API_HOST:https://api-pl.thuanle.me
      - API_HOST:https://api-pl.thuanle.me
    pull_policy: always