services:
  database:
    image: mongo
    restart: always
    volumes:
      - law-fulldev-database:/data/db
  frontend:
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
      - frontend-dev-node-module:/workspace/FE/node_modules
    command: sleep infinity
    network_mode: service:backend
  backend:
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
      - backend-dev-node-module:/workspace/BE/node_modules
    command: sleep infinity
    network_mode: service:database
volumes:
  law-fulldev-database:
  frontend-dev-node-module:
  backend-dev-node-module:
